export const GET_TODOS_BEGIN = "GET_TODOS_BEGIN";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_ERROR = "GET_TODOS_ERROR";

export const CREATE_TODO_BEGIN = "CREATE_TODO_BEGIN";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_ERROR = "CREATE_TODO_ERROR";

export const DELETE_TODO_BEGIN = "DELETE_TODO_BEGIN";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_ERROR = "DELETE_TODO_ERROR";

export const UPDATE_TODO_BEGIN = "UPDATE_TODO_BEGIN";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_ERROR = "UPDATE_TODO_ERROR";

export const CREATE_USER_BEGIN = "UPDATE_TODO_BEGIN";
export const CREATE_USER_SUCCESS = "UPDATE_TODO_SUCCESS";
